// Generated by CoffeeScript 1.9.3
var createHttp, err404, fs, http, mime, path, url;

http = require('http');

fs = require('fs');

url = require('url');

path = require('path');

mime = require('mime-types');

err404 = function(res) {
  res.writeHead(404, {
    "Content-Type": "text/html"
  });
  return res.end("<h1>404 Read Error</h1>");
};

createHttp = function(port, root, cb) {
  var webHttp;
  webHttp = http.createServer(function(req, res) {
    var ext, filePath, pathName, reqUrl, stream;
    reqUrl = req.url;
    pathName = url.parse(reqUrl).pathname;
    ext = path.extname(pathName);
    if (pathName.charAt(pathName.length - 1) === '/') {
      pathName += 'index.html';
    }
    filePath = path.join(root, pathName);
    stream = '';
    if (pathName === '/config.json') {
      filePath = 'config.json';
    }
    if (fs.existsSync(filePath)) {
      res.writeHead(200, {
        'Content-Type': mime.lookup(filePath)
      });
      stream = fs.createReadStream(filePath, {
        flags: "r",
        encoding: null
      });
      stream.on('error', function() {
        return err404(res);
      });
      return stream.pipe(res);
    } else {
      return err404(res);
    }
  });
  webHttp.on('error', function(e) {
    return console.log(e.message);
  });
  webHttp.listen(port);
  cb();
  return webHttp;
};

module.exports = createHttp;
